; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 9600
lib_deps =
    ;arkhipenko/TaskScheduler@^4.0.4
    https://github.com/LiquidCGS/FastIMU@^1.2.8
    https://github.com/belem2050/LightTaskScheduler@^1.1.0
    https://github.com/arduino-libraries/ArduinoMqttClient@^0.1.8