//
// Created by HP Envy on 22/02/2026.
//

#ifndef SSL_ANNE_MAIN_PINOUT_H
#define SSL_ANNE_MAIN_PINOUT_H

#define PIN_MOTDR_R1_FOR 36
#define PIN_MOTDR_R1_BAC 37
#define PIN_MOTDR_R2_FOR 38
#define PIN_MOTDR_R2_BAC 39

#define PIN_MOTDR_R1_SPD 2
#define PIN_MOTDR_R2_SPD 3

#define PIN_MOTDR_L1_FOR 40
#define PIN_MOTDR_L1_BAC 41
#define PIN_MOTDR_L2_FOR 42
#define PIN_MOTDR_L2_BAC 43

#define PIN_MOTDR_L1_SPD 4
#define PIN_MOTDR_L2_SPD 5

#define PIN_MOTKICK_FOR 44
#define PIN_MOTKICK_BAC 45
#define PIN_MOTPUMP_IN 46
#define PIN_MOTPUMP_OUT 47

#define PIN_MOTKICK_SPD 6
#define PIN_MOTPUMP_SPD 7

#define SERIAL_BAUD 115200

#endif //SSL_ANNE_MAIN_PINOUT_H